apiVersion: v1
kind: ConfigMap
metadata:
  name: config-repo
  namespace: bidflow
data:
  api-gateway.yml: |
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://localhost:30080/realms/bidflow
              jwk-set-uri: http://keycloak:8080/realms/bidflow/protocol/openid-connect/certs

      cloud:
        gateway:
          default-filters:
            - AddRequestHeader=X-Gateway-Name, BidFlow API Gateway

          routes:
            - id: auction-service
              uri: http://auction-service:8080
              predicates:
                - Path=/api/auctions/**
              filters:
                - StripPrefix=1

            - id: bid-service
              uri: http://bid-service:8080
              predicates:
                - Path=/api/bids/**
              filters:
                - StripPrefix=1
